import type { NextPage } from 'next'
import Head from 'next/head'
import SideBar from '../components/SideBar'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>What&apos;s App</title>
        <meta name='description' content='Generated by Phi Dinh' />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SideBar />
    </div>
  )
}

export default Home
